"use client";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/utility/Navbar";
import NavbarMobile from "@/components/utility/NavbarMobile";
import CursorTrailCanvas from "@/components/utility/cursor-trail-canvas";
import useLenis from '@/hooks/useLenis';
import favicon from "@/assets/favicon.ico"

const metadata: Metadata = {
  title: "Akash Kumar",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useLenis();
  return (
    <html lang="en"> 
      <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
      <body className="antialiased overflow-x-hidden bg-black select-none"> 
          <Navbar />
          <NavbarMobile />
          <CursorTrailCanvas className="pointer-events-none fixed inset-0 -z-10 h-full w-full md:block" />
          {children}
      </body>
    </html>
  );
}
