import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import CursorTrailCanvas from "@/components/cursor-trail-canvas";
import Favicon from "@/assets/favicon.ico"; // Importing as a module
import NavbarMobile from "@/components/NavbarMobile";

export const metadata: Metadata = {
  title: "Akash Kumar",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href={Favicon.src} type="image/x-icon" />
      <body
        className={` antialiased overflow-x-hidden bg-black select-none`}>
        <Navbar />
        <NavbarMobile />
        <CursorTrailCanvas className="pointer-events-none fixed inset-0 -z-10 h-full w-full  md:block" />
        {children}
      </body>
    </html>
  );
}
